[build]
  base = "dsa-visualise"
  publish = "dsa-visualise/dist"
  command = "npm install --legacy-peer-deps && npm run build"

[functions]
  directory = "dsa-visualise/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
